# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site title and description
title:              Desk
description:        Cue Band FAQ site.

# Site subpath, e.g. /blog
baseurl:            ""

# Permalink URLs structure, for permalink style options see: https://jekyllrb.com/docs/permalinks/
permalink:          /:title/

# Site base hostname & protocol, e.g. http://example.com
url:                "https://faq.cue.band"

# Site logo, dark and light depending on page hero text setting dark/light
logo_image:
    light:          image.png  # e.g. logo.png, upload logo image file to /assets/posts/ folder
    dark:           logo_1.png  # e.g. logo.png, upload logo image file to /assets/posts/ folder

# Author settings, displayed on about page
# author:
#     name:           John Smith
#     email:
#     website:
#     facebook:       https://www.facebook.com/
#     flickr:
#     dribbble:
#     github:
#     googleplus:
#     instagram:      https://www.instagram.com/
#     linkedin:
#     pinterest:
#     twitter:        https://twitter.com/
#     vimeo:          https://vimeo.com/
#     youtube:

# Social share buttons
# twitter_username:   somename
# github_username:    somename

# Default footer image settings
footer:
    copyright:      #Made by <a href="https://unbound.studio/">Unbound Studio</a> in Rome, Italy.

# Disqus comments shortname, requires Disqus account https://disqus.com/
disqus:
    shortname:      # 7865

# Google analytics code, get your code here https://www.google.com/analytics/
google_analytics:

# Google maps API key, get your key here: https://developers.google.com/maps/documentation/javascript/get-api-key
google_maps_api_key:

# Path to post content assets directory i.e post images, pdfs etc
post_assets:        /assets/posts/

# Build settings
markdown:           kramdown
highlighter:        rouge

gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

sass:
  style:            compressed

collections:
  faqs:
    output: false
